// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyOSLPdfWAP_CPa-MOBOpE4ZDcGYMm89M',
    appId: '1:320467428323:web:19be2933369cdb5d4076d6',
    messagingSenderId: '320467428323',
    projectId: 'lockin-d9c70',
    authDomain: 'lockin-d9c70.firebaseapp.com',
    storageBucket: 'lockin-d9c70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG7FoSvaX3-mSRCnnrle5M8ddus_TFJ8o',
    appId: '1:320467428323:android:dfeaa26d470d4ca44076d6',
    messagingSenderId: '320467428323',
    projectId: 'lockin-d9c70',
    storageBucket: 'lockin-d9c70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYm6aeZZsFBG-1K9rRmKK45PgLEZz7Au0',
    appId: '1:320467428323:ios:1beab2809cc1c3ff4076d6',
    messagingSenderId: '320467428323',
    projectId: 'lockin-d9c70',
    storageBucket: 'lockin-d9c70.firebasestorage.app',
    iosClientId: '320467428323-9jvug2medav266i6vb8v2924dghobn76.apps.googleusercontent.com',
    iosBundleId: 'com.example.lockIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYm6aeZZsFBG-1K9rRmKK45PgLEZz7Au0',
    appId: '1:320467428323:ios:1beab2809cc1c3ff4076d6',
    messagingSenderId: '320467428323',
    projectId: 'lockin-d9c70',
    storageBucket: 'lockin-d9c70.firebasestorage.app',
    iosClientId: '320467428323-9jvug2medav266i6vb8v2924dghobn76.apps.googleusercontent.com',
    iosBundleId: 'com.example.lockIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyOSLPdfWAP_CPa-MOBOpE4ZDcGYMm89M',
    appId: '1:320467428323:web:d256eb159b4410fd4076d6',
    messagingSenderId: '320467428323',
    projectId: 'lockin-d9c70',
    authDomain: 'lockin-d9c70.firebaseapp.com',
    storageBucket: 'lockin-d9c70.firebasestorage.app',
  );
}
